# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0006_remove_blog_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='random_url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='random_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
