# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0007_auto_20170515_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='random_url',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='random_url',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
